/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.GeneralPath;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author THANH PHU
 */
public class ImgPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImgPanel
     */
    private BufferedImage image;
    public ImgPanel() {
        initComponents();
         try {
            // Tải ảnh từ resource
            image = ImageIO.read(getClass().getResource("/image/dangNhap_img.png"));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dangNhap_img.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
        Graphics2D g2= (Graphics2D)g;
        g2.setColor(getBackground());
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        GeneralPath path = new GeneralPath();
        int width = getWidth();
        int height = getHeight();
        int arcSize = 20;
        
        path.moveTo(0, arcSize);  // Bắt đầu từ góc trên bên trái
        path.quadTo(0, 0, arcSize, 0);  // Bo góc trên trái
        path.lineTo(width, 0);  // Đường thẳng đến góc trên bên phải (không bo tròn)
        path.lineTo(width, height);  // Đường thẳng xuống góc dưới bên phải
        path.lineTo(arcSize, height);  // Đường thẳng sang góc dưới bên trái
        path.quadTo(0, height, 0, height - arcSize);  // Bo góc dưới bên trái
        path.closePath();
        
        g2.fill(path);
        
//        RoundRectangle2D roundedShape = new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), 20, 20);

            // Cắt ảnh với góc bo tròn
            g2.setClip(path);
            g2.drawImage(image, 0, 0, getWidth(), getHeight(), null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
